---
title: "Abstract Syntax Tree"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ast}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(multimod)
library(lobstr)
library(visNetwork)
```

## Example equation #1
```{r, eval=FALSE}
mm <- example_model$model_info |> as_multimod()
# eq <- example_model$multimod$equations$eqTechCapUp
eq <- mm$equations$eqTechCapUp
print(eq$name); print(eq$desc)
names(eq)
```

### Full tree structure
```{r, eval=FALSE}
depth(eq)
tree(eq, max_depth = 5)
```

### Network representation
```{r, eval=FALSE}
eq_net <- multimod::get_network_data(eq)
visNetwork(eq_net$nodes, eq_net$edges) |>
  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) |>
  visHierarchicalLayout(direction = "LR")  

```

### LaTeX output
```{r, eval=FALSE}
eq_latex <- as_latex(eq)
cat(eq_latex)
write_latex(eq, file = "tmp/test.tex")

```


## Example equation #2
```{r, eval=FALSE}
# eq <- example_model$multimod$equations$eqTechAInp
eq <- mm$equations$eqTechAInp
eq <- mm$equations$eqTechCap
eq <- mm$equations$eqCost
eq <- mm$equations$eqTaxCost
eq <- mm$equations$eqStorageEac
eq <- mm$equations$eqTechSng2Sng
eq <- mm$equations$eqStorageStore
eq <- mm$equations$eqImportIrCost
eq <- mm$equations$eqStorageVarom
eq <- mm$equations$eqTechGrp2Sng
eq <- mm$equations$eqTechAfcOutLo
eq <- mm$equations$eqImportTot
eq <- mm$equations$eqTechEac
eq <- mm$equations$eqAggOutTot
eq <- alias_ast_names(eq, aliases = example_model$short_aliases)
print(eq$name); print(eq$desc)
```

### Partial tree structure
```{r, eval=FALSE}
tree(eq, max_depth = 3)
```

### Network representation
```{r, eval=FALSE}
eq_net <- get_network_data(eq, show_dims = TRUE)
visNetwork(eq_net$nodes, eq_net$edges) |>
  visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) |>
  visInteraction(navigationButtons = TRUE) |>
  visHierarchicalLayout(direction = "LR")
```

### LaTeX output
```{r, eval=FALSE}
eq_w <- remap_ast_elements(eq) 
# eq_latex <- as_latex(eq_w)
# eq_latex <- 
# eq_latex |> cat()

write_latex(eq_w, file = "tmp/test.tex")
write_latex(eq, file = "tmp/test.tex")


mm$equations <- lapply(mm$equations, remap_ast_elements)
mm$equations <- lapply(mm$equations, alias_ast_names, aliases = example_model$short_aliases)
write_latex(mm, file = "tmp/multimod-test.tex")


```

